directories:
  output: C:\Users\89412\Projects\golang\vault\frontend\apps\client\release-build-2
  buildResources: build
appId: com.vault.client
productName: Vault
copyright: Copyright © 2026 Vault
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*
      - package.json
extraFiles:
  - from: build/Vault-Agent.exe
    to: Vault-Agent.exe
electronVersion: 32.2.0
win:
  icon: build/icon.png
  requestedExecutionLevel: requireAdministrator
  target:
    - target: dir
      arch:
        - x64
